# Generated by Django 2.2.1 on 2019-10-08 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_title', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(max_length=100, null=True)),
                ('fax', models.CharField(max_length=100, null=True)),
                ('company_logo', models.CharField(max_length=100, null=True)),
                ('payment_methods', models.ManyToManyField(to='account.PaymentMethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'db_table': 'merchant',
            },
        ),
    ]
